# Generated by Django 3.1.3 on 2021-01-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0003_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemption',
            name='status',
            field=models.CharField(choices=[('a', 'approved'), ('r', 'rejected'), ('p', 'pending')], default='p', max_length=1),
        ),
    ]
