# Generated by Django 3.1.3 on 2020-12-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0002_auto_20201231_1629'),
        ('diploma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma',
            name='competences',
            field=models.ManyToManyField(to='competence.Competence'),
        ),
    ]
