# Generated by Django 3.1.3 on 2020-12-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0002_class_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='competence',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
