# Generated by Django 3.1.3 on 2020-12-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0003_auto_20201228_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exemption',
            old_name='student_id',
            new_name='student',
        ),
        migrations.AddField(
            model_name='diploma',
            name='competences',
            field=models.ManyToManyField(to='diploma.Competence'),
        ),
    ]
