# Generated by Django 3.1.3 on 2021-01-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0003_auto_20210101_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma',
            name='context',
            field=models.TextField(blank=True),
        ),
    ]
