# Generated by Django 3.1.3 on 2020-12-28 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0004_auto_20201228_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diploma',
            old_name='student_id',
            new_name='student',
        ),
    ]
