# Generated by Django 3.1.3 on 2020-12-28 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0005_auto_20201228_2046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='exemption',
            old_name='class_id',
            new_name='course',
        ),
    ]
