# Generated by Django 3.1.3 on 2020-12-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0006_auto_20201228_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
