# Generated by Django 3.1.3 on 2021-01-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0006_auto_20210118_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='back_img',
            field=models.FileField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='front_img',
            field=models.FileField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
