# Generated by Django 3.1.3 on 2020-12-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0007_auto_20201229_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='competences',
            field=models.ManyToManyField(null=True, to='diploma.Competence'),
        ),
    ]
