# Generated by Django 3.1.3 on 2021-01-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0002_auto_20201231_1629'),
        ('diploma', '0008_auto_20210118_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='competences',
            field=models.ManyToManyField(blank=True, to='competence.Competence'),
        ),
    ]
