# Generated by Django 3.1.3 on 2021-02-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0006_auto_20210203_1043'),
        ('diploma', '0010_auto_20210207_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='competences',
            field=models.ManyToManyField(blank=True, to='competence.Competence'),
        ),
    ]
