# Generated by Django 3.1.3 on 2021-01-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='context',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
